### ISSUE TITLE
Request: type hints (e.g. for mypy)

### ISSUE THREAD

**Issue by jamesbraza** [miguelgrinberg/python-socketio#1276]
**Is your feature request related to a problem? Please describe.**

I run `mypy` on my code, and it's throwing errors for not being typed:

```
a.py:19:1: error: Skipping analyzing "socketio": module is installed, but missing library stubs or py.typed marker  [import-untyped]
    from socketio import Client
    ^
```

**Describe the solution you'd like**

Type hints to be added to the repo, or alternately a type stub package to be installable.

**Describe alternatives you've considered**

Disabling mypy for `python-socketio` like the below `pyproject.toml` config:

```toml
[[tool.mypy.overrides]]
# Suppresses error messages about imports that cannot be resolved.
ignore_missing_imports = true
# Per-module configuration options
module = ["socketio.*"]
```
