### ISSUE TITLE
Failed to load resource: the server responded with a status of 502 ()

### ISSUE THREAD

**Issue by dachosen1** [miguelgrinberg/python-socketio#591]
I have been struggling with a socket io, I'm not sure where the problem is, can someone please help. 

#### Socket I.O Client 
```
<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js"
            integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I="
            crossorigin="anonymous">
    </script>

    <script type="text/javascript" charset="utf-8">

      var socket = io.connect('https://' + document.domain + ':' + location.port)

      socket.on('connect', function () {
        socket.emit('audio-streaming', {})
        console.log('Connected')
      })

      socket.on('gender_model', function (ms) {
        $('div.gender-box').text(ms.pred).html()
        $('div.category-prob-gender').text(ms.prob).html()
      })
```

####  Socket I.O Server 
```
@socketio.on('audio-streaming', )
def run_audio_stream(msg):
    p = pyaudio.PyAudio()
    stream = p.open(
        format=FORMAT,
        channels=CHANNELS,
        rate=FRAME["SAMPLE_RATE"],
        input=True,
        stream_callback=callback,
    )
    stream.start_stream()
    while True:
        if len(frames) >= 32:
            socketio.sleep(0.5)

            signal = np.concatenate(tuple(frames))
            # signal = remove_silence(signal)
            wave_period = signal[-FRAME["SAMPLE_RATE"]:].astype(np.float)
            spectrogram = audio_melspectrogram(wave_period)

            # Gender Model
            gender_output, gender_prob = generate_pred(mel=spectrogram, model=model_gender,
                                                       label=Gender.OUTPUT,
                                                       model_name=Gender,
                                                       )
            socketio.emit('gender_model', {'pred': gender_output, 'prob': sigmoid(gender_prob)})
```

####  Error Message  
```
Chrome
Failed to load resource: the server responded with a status of 502 ()

index.js:83 WebSocket connection to 'wss://commvoice.me/socket.io/?EIO=3&transport=websocket&sid=32d9252bd64849939a9b31510011fd8e' failed: WebSocket is closed before the connection is established.

Firefox: 
Firefox can’t establish a connection to the server at wss://commvoice.me/socket.io/?EIO=3&transport=websocket&sid=e53bd5d8a4c54b1bae3c2d892dc045f8.

The connection to wss://commvoice.me/socket.io/?EIO=3&transport=websocket&sid=facd616c3187400d937035125c7564b2 was interrupted while the page was loading.
```
#### Gunicorn 
````
export IS_DEBUG=${DEBUG:-false}
exec gunicorn --bind "0.0.0.0:${PORT:-8080}" -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 run_app:app
````

Nginx: 
```
upstream commvoice {
  server commvoice:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://commvoice;
        proxy_redirect off;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://commvoice/socket.io;
    }
}

server {
    listen 443 ssl;
    ssl_certificate             /etc/letsencrypt/live/commvoice.me/fullchain.pem;
    ssl_certificate_key         /etc/letsencrypt/live/commvoice.me/privkey.pem;
    ssl_trusted_certificate     /etc/letsencrypt/live/commvoice.me/chain.pem;

    location / {
        proxy_pass http://commvoice;
        proxy_redirect off;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass http://commvoice/socket.io;
    }
}
```

##### Docker Compose
```
version: '3.3'

services:
  commvoice:
    build:
      context: .
    image: anelso42/commvoice
    container_name: commvoice
    devices:
      - /dev/snd
    environment:
      - ALSA_PCM=usbstream:CARD=StargazerMicrop
      - XDG_RUNTIME_DIR=/run/user/1000
      - NUMBA_CACHE_DIR=/tmp
      - ALSA_CARD=Generic
    volumes:
      - $HOME/.config/pulse:/usr/src/app/.config/pulse
      - /etc/machine-id:/etc/machine-id:ro
      - /run/user/1001/pulse:/run/user/1001/pulse:ro

    ports:
      - 8080:8080

  nginx:
    build:
      context: ./commonvoice
    container_name: nginx
    depends_on:
      - commvoice
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem
    ports:
      - 80:80
      - 443:443
```

##### Requirements.txt

```
eventlet==0.30.0
Flask==1.1.2
Flask-SocketIO==4.3.2
gevent==20.9.0
gevent-websocket==0.10.1
gunicorn==20.0.4
python-engineio==3.13.2
python-socketio==4.6.1
```

Website: [commvoice.me](https://commvoice.me/)
Repository: [Github](https://github.com/dachosen1/Common-Voice)

**Comment by miguelgrinberg** [comment]
What is `http://commvoice:8080` in your nginx file? That does not seem to be a valid URL.

**Comment by dachosen1** [comment]
@miguelgrinberg  commvoice is the alias for the docker flask application. 
```
networks:
      my-network:
        aliases:
          - commvoice
```
Details here: [docker compose](https://github.com/dachosen1/Common-Voice/blob/master/docker-compose.yml)
